logger:
    level: DEBUG

db:
    url: postgres://roxy:roxy-int-secret@localhost:5433/asr?sslmode=disable  

worker:
    count: 3

filer:
    url: localhost:9000
    user: roxy
    key: roxy-int-secret
    bucket: asr  

transcriber:
    uploadUrl: https://atpazinimas.intelektika.lt/ausis/transcriber/upload
    statusURL: wss://atpazinimas.intelektika.lt/ausis/status.service/subscribe
    resultURL: https://atpazinimas.intelektika.lt/ausis/result.service
    cleanURL: https://atpazinimas.intelektika.lt/ausis/clean.service