version: '3.8'

services:

  upload:
    image: airenas/roxy-upload:${upload_version}
    restart: on-failure
    environment:
      - FILER_URL=minio:9000
      - FILER_KEY=${MINIO_PASS}
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
    ports:
      - 8181:8000

  status:
    image: airenas/roxy-status:${status_version}
    restart: on-failure
    environment:
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
      - WORKER_COUNT=1    
    ports:
      - 8182:8000

  worker:
    image: airenas/roxy-worker:${worker_version}
    restart: on-failure
    environment:
      - WORKER_COUNT=1
      - WORKER_TESTING=true
      - WORKER_CHECKREGISTRY=5s
      - WORKER_RETRYDELAY=5s
      - FILER_URL=minio:9000
      - FILER_KEY=${MINIO_PASS}
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
      # - TRANSCRIBER_UPLOADURL=${TRANSCRIPTION_URL}/ausis/transcriber/upload
      # - TRANSCRIBER_STATUSURL=${TRANSCRIPTION_URL}/ausis/status.service
      # - TRANSCRIBER_RESULTURL=${TRANSCRIPTION_URL}/ausis/result.service
      # - TRANSCRIBER_CLEANURL=${TRANSCRIPTION_URL}/ausis/clean.service
      - DOORMAN_URL=http://integration-tests:9876/doorman
      - CONSUL_HTTP_ADDR=consul:8500
  
  consul:
    image: hashicorp/consul:1.14
    restart: on-failure
    ports:
      - "8500:8500"
    command: "agent"
    volumes:
     - ./cfg/consul/server.json:/consul/config/server.json:ro

  inform:
    image: airenas/roxy-inform:${inform_version}
    restart: on-failure
    environment:
      - WORKER_COUNT=1
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
      - MAIL_URL=http://localhost:7050/tts/results/{{ID}}
      - SMTP_USERNAME=fake@email.com
      - SMTP_FAKEURL=http://integration-tests:9876/fakeURL

  result:
    image: airenas/roxy-result:${result_version}
    restart: on-failure
    environment:
      - FILER_URL=minio:9000
      - FILER_KEY=${MINIO_PASS}
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
    ports:
      - 8183:8000 

  clean:
    image: airenas/roxy-clean:${clean_version}
    restart: on-failure
    environment:
      - FILER_URL=minio:9000
      - FILER_KEY=${MINIO_PASS}
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
    ports:
      - 8184:8000     

  migrate:
    image: airenas/roxy-dbmigrate:${migrate_version}
    command: ["-path", "/migrations", "-database",  "postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  integration-tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      - upload
      - db
      - consul
    environment:
      - UPLOAD_URL=http://upload:8000  
      - STATUS_URL=http://status:8000
      - RESULT_URL=http://result:8000
      - CLEAN_URL=http://clean:8000  
      - DB_URL=postgres://roxy:${PSQL_PASS}@db:5432/asr?sslmode=disable
      - CONSUL_URL=http://consul:8500   
    volumes:
      - ../../:/go/src/
    command: -tags integration -v -count=1 ./testing/integration/...      

  db:
    image: postgres:15.1-alpine3.16
    restart: on-failure
    volumes:
    #   - db-data:/var/lib/postgresql/data
    - ./cfg/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASS}
      - POSTGRES_INITDB_ARGS=--auth=password
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 20

  minio:
    image: minio/minio:RELEASE.2022-11-10T18-20-21Z
    restart: on-failure
    volumes:
     - ./data/minio:/data
    environment:
     - MINIO_ROOT_USER=roxy
     - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    ports:
      - 9000:9000
      - 9090:9090
    command: ["server", "/data", "--console-address", ":9090"]  
