name: Snyk vulnerabilities Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [upload, dbmigrate, worker, status, result, inform, clean]
    steps:
      - uses: actions/checkout@v2

      - name: Build containers ${{ matrix.container }}
        run: make docker/${{ matrix.container }}/build migrate_version=latest upload_version=latest worker_version=latest status_version=latest result_version=latest inform_version=latest clean_version=latest 

      - name: Run Snyk to check ${{ matrix.container }} Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: airenas/roxy-${{ matrix.container }}:latest
          args: --file=build/${{ matrix.container }}/Dockerfile

      - name: Make sarif file copy
        run: mv snyk.sarif snyk-${{ matrix.container }}.sarif

      - name: Replace security-severity undefined for license-related findings 
        run: sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif

      - name: Upload snyk ${{ matrix.container }} result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-${{ matrix.container }}.sarif
          category: ${{ matrix.container }}-analysis
          